[versions]

javaCompile = "17" # ВРЕМЕННО для JitPack: 25 недоступен через toolchain auto-download в их песочнице
javaTarget = "17"

androidGradle = "9.2.1" # https://developer.android.com/reference/tools/gradle-api
kompress = "2.3.1"
kotlin = "2.4.0" # https://github.com/JetBrains/kotlin/releases
kotlinxIo = "0.9.1" # https://github.com/Kotlin/kotlinx-io/releases
kotlinxDateTime = "0.8.0" # https://github.com/Kotlin/kotlinx-datetime/releases
kotlinBrowser = "2026.7.0" # https://github.com/JetBrains/kotlin-wrappers/releases
dokka = "2.2.0" # https://github.com/Kotlin/dokka/releases
karmaConventions = "1.18.2" # https://github.com/karmakrafts/karma-conventions/tags
oshi = "7.3.2" # https://github.com/oshi/oshi/releases
karbide = "1.10.5" # https://github.com/karmakrafts/Karbide/releases

# kompress-benchmarks

kotlinxBenchmark = "0.4.17" # https://github.com/Kotlin/kotlinx-benchmark/releases
jmh = "1.37" # https://github.com/openjdk/jmh/tags

[libraries]

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-wrappers-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlinBrowser" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinxIo" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
karbide-core = { module = "dev.karmakrafts.karbide:karbide-core", version.ref = "karbide" }

# kompress-benchmarks

kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinxBenchmark" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }

[plugins]

android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }

# kompress-benchmarks

kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinxBenchmark" }